import os
import sys
import warnings
import pandas as pd
from datasets import Dataset

# Ignore deprecation warnings to keep stdout clean
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Add parent directory to path to allow importing from backend
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from rag.pipeline import RAGPipeline
from rag.generator import load_env
from ragas import evaluate
from ragas.metrics import Faithfulness, AnswerRelevancy, ContextRecall, ContextPrecision
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

def run_evaluation():
    # 1. Load API Key
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    env_vars = load_env(os.path.join(root_dir, ".env.local"))
    api_key = env_vars.get("GEMINI_KEY") or env_vars.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_KEY or GEMINI_API_KEY not found in .env.local")
        sys.exit(1)
        
    os.environ["GOOGLE_API_KEY"] = api_key

    # Configure stdout to handle UTF-8 if outputting to Windows terminal
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except AttributeError:
            import io
            if not isinstance(sys.stdout, io.TextIOWrapper) or sys.stdout.encoding != 'utf-8':
                sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', write_through=True)

    print("=" * 60)
    print("PREPARING EVALUATION DATASET (1 key query to fit daily quota)")
    print("=" * 60)

    # 2. Define Golden Dataset (1 query to fit free tier 20 RPD limit)
    eval_data = [
        {
            "question": "ما هي طرق الدفع المتوفرة؟",
            "ground_truth": "طريقة الدفع المقبولة حالياً هي الدفع عند الاستلام (COD) فقط، حيث تقوم بالدفع نقداً لشركة التوصيل عند استلام طلبك."
        }
    ]

    # 3. Instantiate Chatbot Pipeline (using gemini-2.0-flash)
    pipeline = RAGPipeline(model="gemini-3.1-flash-lite")

    # 4. Generate chatbot answers and gather retrieved contexts
    questions = []
    answers = []
    contexts_list = []
    ground_truths = []

    for idx, sample in enumerate(eval_data):
        q = sample["question"]
        gt = sample["ground_truth"]
        print(f"\n[{idx+1}/{len(eval_data)}] Querying Chatbot: '{q}'")
        
        try:
            # Run RAG chatbot
            ans, chunks = pipeline.answer_query(q, k=3)
            
            questions.append(q)
            answers.append(ans)
            
            # Extract plain text content of retrieved chunks
            contexts_list.append([chunk.get("text", "") for chunk in chunks])
            ground_truths.append(gt)
            
            print(f"-> Generated Answer: {ans[:60].replace(chr(10), ' ')}...")
            print(f"-> Retrieved {len(chunks)} context chunks.")
        except Exception as e:
            print(f"Error querying chatbot for '{q}': {e}")

    if not questions:
        print("\nError: No answers were successfully generated by the chatbot. Evaluation aborted.")
        sys.exit(1)

    # 5. Create Dataset for Ragas
    dataset_dict = {
        "question": questions,
        "answer": answers,
        "contexts": contexts_list,
        "ground_truth": ground_truths
    }
    dataset = Dataset.from_dict(dataset_dict)

    print("\n" + "=" * 60)
    print("RUNNING RAGAS EVALUATION USING GEMINI API (gemini-3.1-flash-lite)")
    print("=" * 60)

    # 6. Initialize LangChain models for Ragas evaluation
    eval_llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite", google_api_key=api_key)
    eval_embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001", google_api_key=api_key)

    # 7. Evaluate using Ragas
    try:
        results = evaluate(
            dataset=dataset,
            metrics=[
                Faithfulness(),
                AnswerRelevancy(),
                ContextRecall(),
                ContextPrecision()
            ],
            llm=eval_llm,
            embeddings=eval_embeddings
        )
        
        # Convert results to DataFrame and display
        df_results = results.to_pandas()
        
        print("\n=== EVALUATION SUCCESSFUL ===")
        print("\nAverage Metric Scores:")
        for col in df_results.columns:
            if col not in ["question", "answer", "contexts", "ground_truth"]:
                try:
                    mean_score = df_results[col].mean()
                    print(f"  - {col}: {mean_score:.4f}")
                except Exception:
                    pass
            
        print("\nDetailed Question-wise Scores:")
        cols_to_print = [c for c in ["question", "user_input", "answer", "response", "faithfulness", "answer_relevancy", "context_recall", "context_precision"] if c in df_results.columns]
        print(df_results[cols_to_print])
        
        # Save results to disk
        out_path = os.path.join(os.path.dirname(__file__), "evaluation_results.csv")
        df_results.to_csv(out_path, index=False, encoding='utf-8-sig')
        print(f"\nDetailed evaluation results saved to: {out_path}")
        
    except Exception as e:
        print(f"\nError running Ragas evaluation: {e}")

if __name__ == "__main__":
    run_evaluation()
